version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: um-oic-auth-tls
    restart: unless-stopped
    ports:
      - "443:8443"    # HTTPS
      - "80:8080"     # HTTP (für ACME/redirects)
    environment:
      - RUST_LOG=info
      - AUTH_TLS_ENABLE=true
      - AUTH_TLS_BIND=0.0.0.0:8443
      - AUTH_BIND=0.0.0.0:8080
      - DOMAIN=auth.localhost
      - TLS_CERT_PATH=/app/certs/cert.pem
      - TLS_KEY_PATH=/app/certs/key.pem
      - TLS_AUTO_GENERATE=true
      - AUTH_DATA_DIR=/app/data
      - AUTH_DEBUG=false
    volumes:
      - auth-data:/app/data
      - auth-certs:/app/certs
      - ./data/web:/app/data/web:ro
    networks:
      - um-oic-net
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:8443/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  admin-service:
    build:
      context: .
      dockerfile: admin-service/Dockerfile
    container_name: um-oic-admin-tls
    restart: unless-stopped
    ports:
      - "8443:8443"   # HTTPS
      - "8080:8080"   # HTTP
    environment:
      - RUST_LOG=info
      - ADMIN_TLS_ENABLE=true
      - ADMIN_TLS_BIND=0.0.0.0:8443
      - ADMIN_BIND=0.0.0.0:8080
      - DOMAIN=admin.localhost
      - TLS_CERT_PATH=/app/certs/cert.pem
      - TLS_KEY_PATH=/app/certs/key.pem
      - TLS_AUTO_GENERATE=true
      - ADMIN_DATA_DIR=/app/data
      - AUTH_SERVICE_URL=https://auth-service:8443
      - ADMIN_DEBUG=false
    volumes:
      - admin-data:/app/data
      - admin-certs:/app/certs
      - ./admin-web/dist:/app/data/web:ro
    networks:
      - um-oic-net
    depends_on:
      auth-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:8443/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # Optional: Let's Encrypt companion für echte Zertifikate
  acme-companion:
    image: nginxproxy/acme-companion:2.2
    container_name: acme-companion
    restart: unless-stopped
    environment:
      - DEFAULT_EMAIL=admin@yourdomain.com
    volumes:
      - auth-certs:/etc/nginx/certs/auth
      - admin-certs:/etc/nginx/certs/admin
      - acme-challenges:/usr/share/nginx/html
    networks:
      - um-oic-net
    profiles:
      - production

volumes:
  auth-data:
    name: um-oic-auth-data
  admin-data:
    name: um-oic-admin-data
  auth-certs:
    name: um-oic-auth-certs
  admin-certs:
    name: um-oic-admin-certs
  acme-challenges:
    name: um-oic-acme-challenges

networks:
  um-oic-net:
    name: um-oic-network
    driver: bridge