# TLS-enabled Cargo.toml für auth-service
[package]
name = "auth-service"
version = "0.1.0"
edition = "2021"

[dependencies]
# Web Framework mit TLS
axum = { version = "0.7", features = ["macros"] }
axum-server = { version = "0.6", features = ["tls-rustls"] }
tokio = { version = "1", features = ["full"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["fs", "cors", "trace", "request-id"] }

# TLS Implementation
rustls = "0.22"
rustls-pemfile = "2.0"
tokio-rustls = "0.25"

# ACME Client für automatische Zertifikate
instant-acme = "0.5"
rcgen = "0.12"  # Für self-signed certs in development

# Existing dependencies...
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"

# Auth/Crypto
argon2 = "0.5"
jsonwebtoken = "9.2"
rand = "0.8"
rand_core = { version = "0.6", features = ["getrandom"] }
totp-rs = "5.4"
sha2 = "0.10"

# Utilities
uuid = { version = "1.6", features = ["serde", "v4"] }
time = { version = "0.3", features = ["serde", "formatting", "parsing"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json", "env-filter"] }
anyhow = "1.0"
thiserror = "1.0"
clap = { version = "4.4", features = ["derive", "env"] }

# System
libc = "0.2"